import esbuild from "esbuild";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

const banner = `/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outdir = process.env.HFL_OUT ?? "dist";

mkdirSync(outdir, { recursive: true });

const copyAssets = () => {
	copyFileSync("manifest.json", resolve(outdir, "manifest.json"));
	copyFileSync("styles.css", resolve(outdir, "styles.css"));
};

const copyAssetsPlugin = {
	name: "copy-assets",
	setup(build) {
		build.onEnd(() => {
			copyAssets();
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: resolve(outdir, "main.js"),
	plugins: [copyAssetsPlugin],
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
	},
	minify: prod,
});

if (prod) {
	await context.rebuild();
	await context.dispose();
	process.exit(0);
} else {
	await context.watch();
	console.log(`HfL: watching, output → ${outdir}`);
}
